### PR TITLE
providers: WithCachedCode should accept AnyProvider and make it compatible

### LINKED ISSUE #133: providers: Incompatibility Between `WithCachedCode()` and `ethers.JsonRpcProvider`
The provider parameter passed to `providers.WithCachedCode()` appears to be incompatible with `ethers.JsonRpcProvider`.

### Type error
```sh
Provider is not assignable to parameter of type
Type 'Provider' is missing the following properties from type 'Provider': getStorageAt, getAddress
```

### Reproducible example
```ts
import { ethers } from "ethers";

function invokeAutoload(bytecode: string) {
    const provider = new ethers.JsonRpcProvider(config.rpc);
    const cachedCodeProvider = whatsabi.providers.WithCachedCode(
      provider, // Type error
      {
        [address]: bytecode,
      }
    );
    // ...
}
```

### Proposed Fix
```diff
- export function WithCachedCode(provider: Provider, codeCache: Record<string, string>): Provider {
+ export function WithCachedCode(provider: Provider, codeCache: Record<string, string>): AnyProvider {
    return {
        ...provider,
        async getCode(address: string): Promise<string> {
            if (codeCache[address]) {
                return codeCache[address];
            }
            return await provider.getCode(address);
        }
    };
}
```

If this solution seems appropriate, I’d be happy to go ahead and create a pull request.

### PR DESCRIPTION
**Pull request by shazow**
Fixes #133

### CODE REVIEW

**Comment by shazow** [comment]
Going to merge quickly for the sake of getting a minor release out with this fix, but feedback/suggestions are still welcome after closing!

**Comment by yohamta** [comment]
@shazow, do you think it might make sense to modify WithCachedCode like this? It looks like the created provider doesn't include the prototype chain in the current implementation.

```ts
export function WithCachedCode(provider: AnyProvider, codeCache: Record<string, string>): Provider {
    const compatibleProvider = CompatibleProvider(provider)
    const p = Object.create(compatibleProvider); // use compatibleProvider as the prototype
    p.getCode = async (address: string) =>{
            if (codeCache[address]) {
                return codeCache[address];
            }
            const code = await compatibleProvider.getCode(address);
            codeCache[address] = code;
            return code;
        };
    return p;
}
```

**Comment by shazow** [comment]
You're right, that makes more sense! I'll make the change.

**Comment by shazow** [comment]
Just a heads up, I'm avoiding making this into a self-updating cache, at least for now. That expands the scope quite a bit, as it would balloon in memory usage quite fast if not used carefully, so I'd prefer to leave that for the consumer to implement for now.

That said, you're of course welcome to make any kind of compatible provider object and pass it in, and I would expect whatsabi to happily work with it. :)

**Pull request merged**
