### PR TITLE
ethers.js -> ox

### LINKED ISSUE #151: refactor: Use Ox
WhatsABI only has one runtime dependency right now, and it's ethers.js v6. We should look into using this new lower-level library Ox instead: https://oxlib.sh/

There's only a couple of small places in the main library where we use ethers.js helpers:
https://github.com/search?q=repo%3Ashazow%2Fwhatsabi+path%3Asrc%2F*.ts+%22from+%5C%22ethers%5C%22%22&type=code

Then several more helpers for tests, but that can happen later.

### PR DESCRIPTION
**Pull request by shazow**
Closes  #151

### CODE REVIEW

**Comment by shazow** [comment]
This increases the bundle 15.34 kb -> 23.61 kb (54%). Pretty substantialy, need to decide if it's worth it.

Before:

```
  lib.esm/index.js
  Size limit: 20 kB
  Size:       15.34 kB with all dependencies, minified and gzipped

  lib.cjs/index.js
  Size limit: 165 kB
  Size:       163.64 kB with all dependencies, minified and gzipped
```

After:

```
  lib.esm/index.js
  Package size limit has exceeded by 3.62 kB
  Size limit: 20 kB
  Size:       23.61 kB with all dependencies, minified and gzipped

  lib.cjs/index.js
  Package size limit has exceeded by 24.09 kB
  Size limit: 165 kB
  Size:       189.09 kB with all dependencies, minified and gzipped
```

@jxom Am I doing anything obviously wrong here?

**Comment by jxom** [comment]
Try import from `ox/*` instead of the root namespace.

**Comment by shazow** [comment]
@jxom Updated in 4be0a081260b37fe419b87eb7d506f4a6e39d9b1, cjs bundle is smaller now, but esm is still roughyl the same.

```
  lib.esm/index.js
  Package size limit has exceeded by 3.18 kB
  Size limit: 20 kB
  Size:       23.18 kB with all dependencies, minified and gzipped

  lib.cjs/index.js
  Size limit: 165 kB
  Size:       31.43 kB with all dependencies, minified and gzipped
```

**Comment by jxom** [comment]
Ah, found the culprit. Looks like [these guys](https://github.com/wevm/ox/blob/main/src/core/AbiItem.ts#L111-L113) are affecting the tree-shaking process. Going to refactor things a bit to fix.

**Comment by shazow** [comment]
Thanks for investigating 🙏

**Comment by jxom** [comment]
CleanShot 2024-11-15 at 10 38 50@2x

wooo, releasing new version now

**Comment by jxom** [comment]
Can you try update to `ox@0.2.0`?

**Comment by jxom** [comment]
```
 ✓ src/selectors.bench.ts (2) 1218ms
   ✓  (2) 1216ms
     name                                  hz     min     max    mean     p75     p99    p995    p999     rme  samples
   · selectorsFromBytecode (ox)      2,273.48  0.3985  1.3748  0.4399  0.4401  0.6035  0.7232  1.0234  ±0.68%     1137   fastest
   · selectorsFromBytecode (ethers)    898.17  1.0256  1.6729  1.1134  1.1266  1.3229  1.3568  1.6729  ±0.45%      450


 BENCH  Summary

  selectorsFromBytecode (ox) - src/selectors.bench.ts >
    2.53x faster than selectorsFromBytecode (ethers)
 ```

**Comment by shazow** [comment]
Looking much better, thank you!

```
  lib.esm/index.js
  Size limit: 20 kB
  Size:       13.87 kB with all dependencies, minified and gzipped

  lib.cjs/index.js
  Size limit: 165 kB
  Size:       31.15 kB with all dependencies, minified and gzipped
```

**Pull request merged**
